services:
  - type: web
    name: boknowshouses-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    envVars:
      - key: GHL_API_KEY
        sync: false
      - key: GHL_LOCATION_ID
        sync: false
    autoDeploy: true
    plan: free
